require('Timer')
require('Encoders')
require('Instances')
require('Buttons')
require('LEDs')
require('Midi.Midi')
require('Prop.Prop')
require('views.Views')
require('Patches')
require('Modules')
require('InputOutput')
require('Miwos')

Patches.load('patch1')
Views.activate('Patch')
