require('Bridge')
require('Timer')
require('Encoders')
require('Buttons')
require('LEDs')
require('Midi.Midi')
require('Prop.Prop')
require('Interface')
require('Patches')
require('Modules')
require('Miwos')

Patches.load('patch1')

Modules.getInfo('Input')
